apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-buildagent
  labels:
    app: azdevops-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: kubepodcreation
        image: <acr-server>/dockeragent:latest
        envFrom:
        - configMapRef:
            name: azdevops
        - secretRef:
            name: azdevops